# Generated by Django 3.1.5 on 2022-04-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutDoorSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'выездная школа',
                'verbose_name_plural': 'выездные школы',
            },
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='secret_key',
            field=models.CharField(default='xcgOYLlVyLWJlJhydOWn', max_length=20),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outdoor_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history_main.outdoorschool')),
            ],
            options={
                'verbose_name': 'картинка для выездной школы',
                'verbose_name_plural': 'картинки для выездной школы',
            },
        ),
    ]
