# Generated by Django 3.1.5 on 2022-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0004_auto_20220426_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='secret_key',
            field=models.CharField(default='chkQnLGXHaFNSgkQihKG', max_length=20),
        ),
    ]
