# Generated by Django 3.1.5 on 2021-04-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_main', '0013_auto_20210429_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='history_main.Tag'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='secret_key',
            field=models.CharField(default='yaPRCDockWlMTxmKUhRH', max_length=20),
        ),
    ]
